//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXOProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust
    {
        public Cust()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CID { get; set; }
        public int UID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string NOKName { get; set; }
        public string NOKContact { get; set; }
        public string NOKAddress { get; set; }
        public string Passport { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
