//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXOProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Custs = new HashSet<Cust>();
        }
    
        public int UID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Security_Question { get; set; }
        public string Answer { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Cust> Custs { get; set; }
    }
}
