//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXOProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OID { get; set; }
        public int RID { get; set; }
        public int CID { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime DateOut { get; set; }
        public int PaxCount { get; set; }
        public int RoomCount { get; set; }
        public string SpecialRequest { get; set; }
    
        public virtual Cust Cust { get; set; }
        public virtual Room Room { get; set; }
    }
}
