//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryTeam8A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public short BookID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public Nullable<short> TotalStock { get; set; }
        public Nullable<short> NumberLended { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
